sudo: true
notifications:
  email:
    on_success: change
    on_failure: always
go_import_path: github.com/xor-gate/debpkg
language: go
go:
  - 1.6
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - make test
  - make test-dpkg
  - sudo dpkg --install debpkg-test.deb
  - sudo dpkg --remove debpkg-test
  - sudo dpkg --install debpkg-test-signed.deb
  - $HOME/gopath/bin/goveralls -service=travis-ci
